### ISSUE TITLE
MIT or LGPL License?

### ISSUE THREAD

**Issue by tanghongxin** [BoBoooooo/Element-Pro-Crud#10]
I've found a 'MIT' field in package.json while the LICENSE file is marked as LGPL, which would be correct?

**Comment by BoBoooooo** [comment]
Thanks for your feedback~
LGPL has been changed to MIT~

**Comment by tanghongxin** [comment]
> Thanks for your feedback~
> LGPL has been changed to MIT~

Well. After viewing the source code, I've found that this project is built on [vue-form-making](https://github.com/GavinZhuLei/vue-form-making) which use LGPL license. Is it allowed to use MIT instead of LGPL?

**Comment by BoBoooooo** [comment]
Yes, but it was developed on the basis of open source version 3 years ago, and it was still MIT protocol.

I asked the author that the LGPL protocol should be maintained at the moment.

Respect for the original , So LGPL is more legal. 

I'll revise license again.

**Comment by BoBoooooo** [comment]
> > Thanks for your feedback~
> > LGPL has been changed to MIT~
> 
> Well. After viewing the source code, I've found that this project is built on [vue-form-making](https://github.com/GavinZhuLei/vue-form-making) which uses LGPL license. Is it allowed to use MIT instead of LGPL?

Yes, but it was developed on the basis of open source version 3 years ago, and it was still MIT protocol.

I asked the author that the LGPL protocol should be maintained at the moment.

Respect for the original , So LGPL is more legal.

I'll revise license again.
