### ISSUE TITLE
大佬有交流群嘛？

### ISSUE THREAD

**Issue by zhoujingfu** [BoBoooooo/Element-Pro-Crud#18]
本地跑装包有些问题，有交流群讨论下嘛？

**Comment by BoBoooooo** [comment]
暂时没有…直接issue里反馈吧，具体什么问题

zhoujingfu ***@***.***>于2022年1月20日 周四下午5:32写道：

**Comment by zhoujingfu** [comment]
![image](https://user-images.githubusercontent.com/43539608/150449751-eed67da7-bc03-4caa-a8cb-f90a95787a24.png)
尝试过好多方式，暂时没定位到啥问题
