### ISSUE TITLE
大哥 请问一下 支持表格导入吗？ 我有表格 但是感觉不方便 想要用这个 

### ISSUE THREAD

**Issue by charlesouwen** [BoBoooooo/Element-Pro-Crud#7]

**Comment by BoBoooooo** [comment]
不好意思没太注意issue ..

表格导入是指excel导入么

**Comment by BoBoooooo** [comment]
ProTable右上角功能按钮有预留插槽 导入这块功能可以自己实现,默认没有集成进来。

http://procrud.fun/frameworks/ProTable.html#props-%E8%A1%A5%E5%85%85%E8%AF%B4%E6%98%8E
