### ISSUE TITLE
请问能不能把在线示例那里的完整配置给预览出来看，看文档配置还是有点云里雾里的感觉

### ISSUE THREAD

**Issue by CHANCCCZQ** [BoBoooooo/Element-Pro-Crud#9]
请问能不能把在线示例那里的完整配置给预览出来看，看文档配置还是有点云里雾里的感觉

**Comment by BoBoooooo** [comment]
你好感谢反馈，我这边抽空会继续完善文档。

生产环境示例的话可以看一下 https://github.com/BoBoooooo/BoBo-Vue-Admin

在线示例表单部分的 demo在 https://github.com/BoBoooooo/Element-Pro-Crud/tree/master/src/demo/component/examples

**Comment by CHANCCCZQ** [comment]
> 你好感谢反馈，我这边抽空会继续完善文档。
> 
> 生产环境示例的话可以看一下 https://github.com/BoBoooooo/BoBo-Vue-Admin
> 
> 在线示例表单部分的 demo在 https://github.com/BoBoooooo/Element-Pro-Crud/tree/master/src/demo/component/examples

好的，感谢您
